export const POI_MIN_RENDER_ZOOM = 12;

export const POI_IMAGES: Record<string, number> = {
  'poi-default': require('../assets/icons/poi/ic_place_48px.png'),
  'poi-hospital': require('../assets/icons/poi/ic_local_hospital_48px.png'),
  'poi-hotel': require('../assets/icons/poi/ic_hotel_48px.png'),
  'poi-restaurant': require('../assets/icons/poi/ic_restaurant_48px.png'),
  'poi-cafe': require('../assets/icons/poi/ic_local_cafe_48px.png'),
  'poi-pharmacy': require('../assets/icons/poi/ic_local_pharmacy_48px.png'),
  'poi-airport': require('../assets/icons/poi/ic_local_airport_48px.png'),
  'poi-train': require('../assets/icons/poi/ic_train_48px.png'),
  'poi-church': require('../assets/icons/poi/ic_local_church_48px.png'),
  'poi-library': require('../assets/icons/poi/ic_local_library_48px.png'),
  'poi-gas': require('../assets/icons/poi/ic_local_gas_station_48px.png'),
  'poi-grocery': require('../assets/icons/poi/ic_local_grocery_store_48px.png'),
  'poi-bank': require('../assets/icons/poi/ic_local_atm_48px.png'),
  'poi-parking': require('../assets/icons/poi/ic_local_parking_48px.png'),
  'poi-atm': require('../assets/icons/poi/ic_local_atm_48px.png'),
  'poi-mall': require('../assets/icons/poi/ic_local_mall_48px.png'),
  'poi-bar': require('../assets/icons/poi/ic_local_bar_48px.png'),
  'poi-drink': require('../assets/icons/poi/ic_local_drink_48px.png'),
  'poi-pizza': require('../assets/icons/poi/ic_local_pizza_48px.png'),
  'poi-movie': require('../assets/icons/poi/ic_local_movies_48px.png'),
  'poi-terrain': require('../assets/icons/poi/ic_terrain_48px.png'),
  'poi-shipping': require('../assets/icons/poi/ic_local_shipping_48px.png'),
  'poi-play': require('../assets/icons/poi/ic_local_play_48px.png'),
  'poi-post-office': require('../assets/icons/poi/ic_local_post_office_48px.png'),
  'poi-printshop': require('../assets/icons/poi/ic_local_printshop_48px.png'),
  'poi-florist': require('../assets/icons/poi/ic_local_florist_48px.png'),
  'poi-car-wash': require('../assets/icons/poi/ic_local_car_wash_48px.png'),
  'poi-laundry': require('../assets/icons/poi/ic_local_laundry_service_48px.png'),
  'poi-convenience': require('../assets/icons/poi/ic_local_convenience_store_48px.png'),
  'poi-ev': require('../assets/icons/poi/ic_ev_station_48px.png'),
  'poi-traffic': require('../assets/icons/poi/ic_traffic_48px.png'),
  'poi-see': require('../assets/icons/poi/ic_local_see_48px.png'),
  'poi-offer': require('../assets/icons/poi/ic_local_offer_48px.png'),
  'poi-activity': require('../assets/icons/poi/ic_local_activity_48px.png'),
  'poi-transfer': require('../assets/icons/poi/ic_transfer_within_a_station_48px.png'),
};

export const POI_ICON_MATCH_EXPRESSION: any[] = [
  'match',
  ['downcase', ['to-string', ['coalesce', ['get', 'landmark_type'], 'unknown']]],
  'hospital', 'poi-hospital',
  'clinic', 'poi-hospital',
  'hotel', 'poi-hotel',
  'restaurant', 'poi-restaurant',
  'fast_food', 'poi-restaurant',
  'cafe', 'poi-cafe',
  'coffee_shop', 'poi-cafe',
  'pharmacy', 'poi-pharmacy',
  'airport', 'poi-airport',
  'train_station', 'poi-train',
  'station', 'poi-transfer',
  'church', 'poi-church',
  'library', 'poi-library',
  'fuel', 'poi-gas',
  'gas_station', 'poi-gas',
  'supermarket', 'poi-grocery',
  'grocery', 'poi-grocery',
  'bank', 'poi-bank',
  'atm', 'poi-atm',
  'parking', 'poi-parking',
  'mall', 'poi-mall',
  'bar', 'poi-bar',
  'pub', 'poi-bar',
  'nightclub', 'poi-drink',
  'pizza', 'poi-pizza',
  'cinema', 'poi-movie',
  'park', 'poi-terrain',
  'playground', 'poi-play',
  'post_office', 'poi-post-office',
  'copyshop', 'poi-printshop',
  'florist', 'poi-florist',
  'car_wash', 'poi-car-wash',
  'laundry', 'poi-laundry',
  'convenience', 'poi-convenience',
  'charging_station', 'poi-ev',
  'viewpoint', 'poi-see',
  'poi-default',
];
