const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

/**
 * Deploy script for Para Transport smart contracts.
 *
 * Usage:
 *   Testnet:  npx hardhat run scripts/deploy.js --network amoy
 *   Local:    npx hardhat run scripts/deploy.js --network localhost
 *   Mainnet:  npx hardhat run scripts/deploy.js --network polygon
 *
 * After deployment, contract addresses are saved to:
 *   ../deployed-addresses.json  (for reference)
 *   ../.env.blockchain          (copy values to your main .env)
 */
async function main() {
  console.log("\n🚀 Para Transport — Smart Contract Deployment\n");
  console.log("=".repeat(50));

  // Get the deployer account
  const [deployer] = await ethers.getSigners();
  const deployerAddress = await deployer.getAddress();
  const balance = await ethers.provider.getBalance(deployerAddress);

  console.log(`\n📍 Deployer address: ${deployerAddress}`);
  console.log(`💰 Deployer balance: ${ethers.formatEther(balance)} MATIC`);
  console.log(`🌐 Network: ${hre.network.name}\n`);

  if (balance === 0n) {
    throw new Error(
      "Deployer has no MATIC. Get testnet MATIC from: https://faucet.polygon.technology/"
    );
  }

  // ─── Deploy ParaToken (ERC-20) ────────────────────────────────────────────
  console.log("📦 Deploying ParaToken (ERC-20)...");
  const ParaToken = await ethers.getContractFactory("ParaToken");
  const paraToken = await ParaToken.deploy(deployerAddress);
  await paraToken.waitForDeployment();
  const paraTokenAddress = await paraToken.getAddress();
  console.log(`✅ ParaToken deployed at: ${paraTokenAddress}`);

  // ─── Deploy ParaBadge (ERC-721) ───────────────────────────────────────────
  console.log("\n📦 Deploying ParaBadge (ERC-721)...");
  const ParaBadge = await ethers.getContractFactory("ParaBadge");
  const paraBadge = await ParaBadge.deploy(deployerAddress);
  await paraBadge.waitForDeployment();
  const paraBadgeAddress = await paraBadge.getAddress();
  console.log(`✅ ParaBadge deployed at: ${paraBadgeAddress}`);

  // ─── Register badge types ─────────────────────────────────────────────────
  console.log("\n🏅 Registering badge types...");

  // These are placeholder URIs — replace with real IPFS URIs in production
  // Format: ipfs://<CID> pointing to a JSON metadata file
  const badgeTypes = [
    {
      id: "first_ride",
      uri: "ipfs://QmPlaceholder/first_ride.json",
      name: "First Ride",
    },
    {
      id: "10_trips",
      uri: "ipfs://QmPlaceholder/10_trips.json",
      name: "10 Trips",
    },
    {
      id: "50_trips",
      uri: "ipfs://QmPlaceholder/50_trips.json",
      name: "50 Trips",
    },
    {
      id: "streak_7",
      uri: "ipfs://QmPlaceholder/streak_7.json",
      name: "7-Day Streak",
    },
    {
      id: "streak_30",
      uri: "ipfs://QmPlaceholder/streak_30.json",
      name: "30-Day Streak",
    },
    {
      id: "100km",
      uri: "ipfs://QmPlaceholder/100km.json",
      name: "100km Traveled",
    },
  ];

  for (const badge of badgeTypes) {
    const tx = await paraBadge.registerBadgeType(badge.id, badge.uri);
    await tx.wait();
    console.log(`  ✅ Registered: ${badge.name} (${badge.id})`);
  }

  // ─── Save deployed addresses ───────────────────────────────────────────────
  const deployedAddresses = {
    network: hre.network.name,
    chainId: hre.network.config.chainId,
    deployedAt: new Date().toISOString(),
    deployer: deployerAddress,
    contracts: {
      ParaToken: paraTokenAddress,
      ParaBadge: paraBadgeAddress,
    },
  };

  // Save to JSON file for reference
  const outputPath = path.join(__dirname, "../deployed-addresses.json");
  fs.writeFileSync(outputPath, JSON.stringify(deployedAddresses, null, 2));
  console.log(`\n💾 Addresses saved to: deployed-addresses.json`);

  // Generate .env variables to copy
  const envContent = `
# ─── Para Transport Blockchain Config ───────────────────────────
# Generated by deploy.js on ${new Date().toISOString()}
# Network: ${hre.network.name}
# Copy these values to your main .env file

PARA_TOKEN_CONTRACT_ADDRESS=${paraTokenAddress}
PARA_BADGE_CONTRACT_ADDRESS=${paraBadgeAddress}
BLOCKCHAIN_NETWORK=${hre.network.name}
BLOCKCHAIN_CHAIN_ID=${hre.network.config.chainId}
POLYGON_AMOY_RPC_URL=https://rpc-amoy.polygon.technology
`;

  fs.writeFileSync(path.join(__dirname, "../.env.blockchain"), envContent);

  // ─── Final Summary ────────────────────────────────────────────────────────
  console.log("\n" + "=".repeat(50));
  console.log("🎉 Deployment Complete!\n");
  console.log(`ParaToken (PRT):  ${paraTokenAddress}`);
  console.log(`ParaBadge (NFT):  ${paraBadgeAddress}`);

  if (hre.network.name === "amoy") {
    console.log(`\n🔍 View on PolygonScan Testnet:`);
    console.log(
      `   ParaToken:  https://amoy.polygonscan.com/address/${paraTokenAddress}`
    );
    console.log(
      `   ParaBadge:  https://amoy.polygonscan.com/address/${paraBadgeAddress}`
    );
  }

  console.log("\n📋 Next steps:");
  console.log("   1. Copy .env.blockchain values into your main .env");
  console.log("   2. Add DEPLOYER_PRIVATE_KEY to Supabase Edge Function secrets");
  console.log("   3. Update IPFS URIs with real badge metadata");
  console.log("=".repeat(50) + "\n");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\n❌ Deployment failed:", error);
    process.exit(1);
  });
